### PR TITLE
fix(expo-cli version): expo cli version upgrade from 2.6 to 3.0.10

### PR DESCRIPTION
**Pull request by taha437**
## Description

I just updated the version of expo-cli from 2.6 to 3.0.10 because the previous version was unable to open expo dashboard on browser showing only a black screen. A bit of googling and forums led me to this solution.

## Motivation and Context

Upgrading from expo-cli version 2.6 to 3.0.10 resolves the issue of black screen when expo dashboard was opened in browser. It also fixes tunnel related issues when connecting and scanning through expo app.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by artalat** [comment]
In the commit message context is wrong. It should be `expo` rather than `expo-cli version`.

Example:

`fix(expo): expo cli version upgrade from 2.6 to 3.0.10`

**Comment by taha437** [comment]
> In the commit message context is wrong. It should be `expo` rather than `expo-cli version`.
> 
> Example:
> 
> `fix(expo): expo cli version upgrade from 2.6 to 3.0.10`

Corrected!

**Pull request merged**
