### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by IamMHC**

### CODE REVIEW

**Comment by artalat** [comment]
Merging this will no release automatically. Semantic Release needs to be fixed. @hashim-sohail @ammarkhan967

**Comment by hashim-sohail** [comment]
> Merging this will no release automatically. Semantic Release needs to be fixed. @hashim-sohail @ammarkhan967

This job runs on travis, not on GA Actions. So the release would be made 

Need some time to R&D for the PAT issue to  enable pushing to the protected branches.

**Pull request merged**
