### PR TITLE
fix(Storybook): remove @types/storybook__addon-knobs

### PR DESCRIPTION
**Pull request by IamMHC**

### CODE REVIEW

**Comment by artalat** [comment]
"This branch is out-of-date with the base branch"

**Comment by IamMHC** [comment]
@artalat Sir review and merge it please.

**Comment by IamMHC** [comment]
> "This branch is out-of-date with the base branch"

Sir kindly explain

**Comment by IamMHC** [comment]
@artalat  Sir Kindly merge

**Pull request merged**
