### PR TITLE
Updated babel-preset-bluebase

### PR DESCRIPTION
**Pull request by artalat**
Updates the "babel-preset-bluebase" package to add "flow" support.

This is done because a lot of react native modules are create with flow, which cause webpack compilation issues.

### CODE REVIEW

**Comment by artalat** [comment]
@danial24 oclif isn't playing well with `babel-preset-react-native`.

Basically, we need to add `babel-preset-react-native` to `babel-preset-bluebase`, but doing so is causing compile issues here. Can you investigate?

**Comment by danial24** [comment]
@artalat 
Ok, will look into it.

**Pull request merged**
