### PR TITLE
Updated expo-cli version

### PR DESCRIPTION
**Pull request by taha437**
---
name: Updated expo-cli version
about: Version upgrade of expo-cli from 2.6 to 3.0.10.
title: ""
labels: ''"
assignees: 'taha437'

---

## Description

I just updated the version of expo-cli from 2.6 to 3.0.10 because the previous version was unable to open expo dashboard on browser showing only a black screen. A bit of googling and forums led me to this solution.

## Motivation and Context

Upgrading from expo-cli version 2.6 to 3.0.10 resolves the issue of black screen when expo dashboard was opened in browser. It also fixes tunnel related issues when connecting and scanning through expo app.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by artalat** [comment]
A couple of things:

- You cannot merge directly into master. We use git-flow, so PRs always merge into master.
- Please use the updated PR template.

@hassans-be @ammarkhan967 can you guys help?

**Comment by hassans-be** [comment]
@ammarkhan967 where do we stand on this?

**Comment by artalat** [comment]
why was this closed???

**Comment by artalat** [comment]
I see you closed it in favor of #70. Never close without mentioning the reason. 

Example:

> Closing in favor of #70.

**Comment by taha437** [comment]
Yes, because I generated a new PR and tagged you in it. Closed it to remove any redundancy. Okay, perfect will mention the reason from next time. Sorry for any inconveniences.

**Pull request closed without merging**
